[2019-01-27 11:46:22,838] {models.py:1361} INFO - Dependencies all met for <TaskInstance: first_test.run_regression 2019-01-27T00:00:00+00:00 [queued]>
[2019-01-27 11:46:22,843] {models.py:1361} INFO - Dependencies all met for <TaskInstance: first_test.run_regression 2019-01-27T00:00:00+00:00 [queued]>
[2019-01-27 11:46:22,843] {models.py:1573} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 4
--------------------------------------------------------------------------------

[2019-01-27 11:46:23,118] {models.py:1595} INFO - Executing <Task(BashOperator): run_regression> on 2019-01-27T00:00:00+00:00
[2019-01-27 11:46:23,119] {base_task_runner.py:118} INFO - Running: ['bash', '-c', 'airflow run first_test run_regression 2019-01-27T00:00:00+00:00 --job_id 9 --raw -sd DAGS_FOLDER/.ipynb_checkpoints/DAG-checkpoint.py --cfg_path /tmp/tmpn3ppg2tk']
[2019-01-27 11:46:23,644] {base_task_runner.py:101} INFO - Job 9: Subtask run_regression [2019-01-27 11:46:23,644] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-01-27 11:46:23,928] {base_task_runner.py:101} INFO - Job 9: Subtask run_regression [2019-01-27 11:46:23,928] {models.py:271} INFO - Filling up the DagBag from /home/brute/Dropbox/Writing/Blog/andana/assets/notebooks/dags/.ipynb_checkpoints/DAG-checkpoint.py
[2019-01-27 11:46:24,011] {base_task_runner.py:101} INFO - Job 9: Subtask run_regression [2019-01-27 11:46:24,011] {cli.py:484} INFO - Running <TaskInstance: first_test.run_regression 2019-01-27T00:00:00+00:00 [running]> on host localhost.localdomain
[2019-01-27 11:46:24,022] {bash_operator.py:74} INFO - Tmp dir root location: 
 /tmp
[2019-01-27 11:46:24,022] {bash_operator.py:87} INFO - Temporary script location: /tmp/airflowtmp2fyaekmf/run_regressiond4tsvw3y
[2019-01-27 11:46:24,022] {bash_operator.py:97} INFO - Running command: python ~/regress.py
[2019-01-27 11:46:24,026] {bash_operator.py:106} INFO - Output:
[2019-01-27 11:46:25,200] {bash_operator.py:110} INFO - Traceback (most recent call last):
[2019-01-27 11:46:25,200] {bash_operator.py:110} INFO -   File "/home/brute/regress.py", line 49, in <module>
[2019-01-27 11:46:25,200] {bash_operator.py:110} INFO -     df = pd.read_fwf('auto-mpg.data', header=None)
[2019-01-27 11:46:25,201] {bash_operator.py:110} INFO -   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/pandas/io/parsers.py", line 710, in read_fwf
[2019-01-27 11:46:25,201] {bash_operator.py:110} INFO -     return _read(filepath_or_buffer, kwds)
[2019-01-27 11:46:25,201] {bash_operator.py:110} INFO -   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/pandas/io/parsers.py", line 440, in _read
[2019-01-27 11:46:25,201] {bash_operator.py:110} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2019-01-27 11:46:25,202] {bash_operator.py:110} INFO -   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/pandas/io/parsers.py", line 787, in __init__
[2019-01-27 11:46:25,202] {bash_operator.py:110} INFO -     self._make_engine(self.engine)
[2019-01-27 11:46:25,202] {bash_operator.py:110} INFO -   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/pandas/io/parsers.py", line 1024, in _make_engine
[2019-01-27 11:46:25,202] {bash_operator.py:110} INFO -     self._engine = klass(self.f, **self.options)
[2019-01-27 11:46:25,202] {bash_operator.py:110} INFO -   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/pandas/io/parsers.py", line 3445, in __init__
[2019-01-27 11:46:25,203] {bash_operator.py:110} INFO -     PythonParser.__init__(self, f, **kwds)
[2019-01-27 11:46:25,203] {bash_operator.py:110} INFO -   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/pandas/io/parsers.py", line 2077, in __init__
[2019-01-27 11:46:25,203] {bash_operator.py:110} INFO -     memory_map=self.memory_map)
[2019-01-27 11:46:25,203] {bash_operator.py:110} INFO -   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/pandas/io/common.py", line 403, in _get_handle
[2019-01-27 11:46:25,203] {bash_operator.py:110} INFO -     f = open(path_or_buf, mode, errors='replace')
[2019-01-27 11:46:25,204] {bash_operator.py:110} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'auto-mpg.data'
[2019-01-27 11:46:25,339] {bash_operator.py:114} INFO - Command exited with return code 1
[2019-01-27 11:46:25,346] {models.py:1760} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/airflow/models.py", line 1659, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/airflow/operators/bash_operator.py", line 118, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2019-01-27 11:46:25,522] {models.py:1783} INFO - Marking task as UP_FOR_RETRY
[2019-01-27 11:46:25,844] {base_task_runner.py:101} INFO - Job 9: Subtask run_regression Traceback (most recent call last):
[2019-01-27 11:46:25,844] {base_task_runner.py:101} INFO - Job 9: Subtask run_regression   File "/home/brute/apps/anaconda/envs/airflow/bin/airflow", line 32, in <module>
[2019-01-27 11:46:25,844] {base_task_runner.py:101} INFO - Job 9: Subtask run_regression     args.func(args)
[2019-01-27 11:46:25,845] {base_task_runner.py:101} INFO - Job 9: Subtask run_regression   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-01-27 11:46:25,845] {base_task_runner.py:101} INFO - Job 9: Subtask run_regression     return f(*args, **kwargs)
[2019-01-27 11:46:25,845] {base_task_runner.py:101} INFO - Job 9: Subtask run_regression   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/airflow/bin/cli.py", line 490, in run
[2019-01-27 11:46:25,845] {base_task_runner.py:101} INFO - Job 9: Subtask run_regression     _run(args, dag, ti)
[2019-01-27 11:46:25,846] {base_task_runner.py:101} INFO - Job 9: Subtask run_regression   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/airflow/bin/cli.py", line 406, in _run
[2019-01-27 11:46:25,846] {base_task_runner.py:101} INFO - Job 9: Subtask run_regression     pool=args.pool,
[2019-01-27 11:46:25,846] {base_task_runner.py:101} INFO - Job 9: Subtask run_regression   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-01-27 11:46:25,846] {base_task_runner.py:101} INFO - Job 9: Subtask run_regression     return func(*args, **kwargs)
[2019-01-27 11:46:25,846] {base_task_runner.py:101} INFO - Job 9: Subtask run_regression   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/airflow/models.py", line 1659, in _run_raw_task
[2019-01-27 11:46:25,847] {base_task_runner.py:101} INFO - Job 9: Subtask run_regression     result = task_copy.execute(context=context)
[2019-01-27 11:46:25,847] {base_task_runner.py:101} INFO - Job 9: Subtask run_regression   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/airflow/operators/bash_operator.py", line 118, in execute
[2019-01-27 11:46:25,847] {base_task_runner.py:101} INFO - Job 9: Subtask run_regression     raise AirflowException("Bash command failed")
[2019-01-27 11:46:25,847] {base_task_runner.py:101} INFO - Job 9: Subtask run_regression airflow.exceptions.AirflowException: Bash command failed
[2019-01-27 11:46:27,671] {logging_mixin.py:95} INFO - [2019-01-27 11:46:27,670] {jobs.py:2627} INFO - Task exited with return code 1
