[2019-01-27 11:46:43,914] {models.py:1361} INFO - Dependencies all met for <TaskInstance: first_test.run_regression 2019-01-27T00:00:00+00:00 [queued]>
[2019-01-27 11:46:43,921] {models.py:1361} INFO - Dependencies all met for <TaskInstance: first_test.run_regression 2019-01-27T00:00:00+00:00 [queued]>
[2019-01-27 11:46:43,922] {models.py:1573} INFO - 
--------------------------------------------------------------------------------
Starting attempt 4 of 4
--------------------------------------------------------------------------------

[2019-01-27 11:46:44,222] {models.py:1595} INFO - Executing <Task(BashOperator): run_regression> on 2019-01-27T00:00:00+00:00
[2019-01-27 11:46:44,222] {base_task_runner.py:118} INFO - Running: ['bash', '-c', 'airflow run first_test run_regression 2019-01-27T00:00:00+00:00 --job_id 12 --raw -sd DAGS_FOLDER/.ipynb_checkpoints/DAG-checkpoint.py --cfg_path /tmp/tmphwzqo3s6']
[2019-01-27 11:46:44,748] {base_task_runner.py:101} INFO - Job 12: Subtask run_regression [2019-01-27 11:46:44,748] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-01-27 11:46:44,973] {base_task_runner.py:101} INFO - Job 12: Subtask run_regression [2019-01-27 11:46:44,973] {models.py:271} INFO - Filling up the DagBag from /home/brute/Dropbox/Writing/Blog/andana/assets/notebooks/dags/.ipynb_checkpoints/DAG-checkpoint.py
[2019-01-27 11:46:45,037] {base_task_runner.py:101} INFO - Job 12: Subtask run_regression [2019-01-27 11:46:45,037] {cli.py:484} INFO - Running <TaskInstance: first_test.run_regression 2019-01-27T00:00:00+00:00 [running]> on host localhost.localdomain
[2019-01-27 11:46:45,047] {bash_operator.py:74} INFO - Tmp dir root location: 
 /tmp
[2019-01-27 11:46:45,048] {bash_operator.py:87} INFO - Temporary script location: /tmp/airflowtmp2uiww7b3/run_regression19la_hsh
[2019-01-27 11:46:45,048] {bash_operator.py:97} INFO - Running command: python ~/regress.py
[2019-01-27 11:46:45,052] {bash_operator.py:106} INFO - Output:
[2019-01-27 11:46:46,141] {bash_operator.py:110} INFO - Traceback (most recent call last):
[2019-01-27 11:46:46,142] {bash_operator.py:110} INFO -   File "/home/brute/regress.py", line 49, in <module>
[2019-01-27 11:46:46,142] {bash_operator.py:110} INFO -     df = pd.read_fwf('auto-mpg.data', header=None)
[2019-01-27 11:46:46,142] {bash_operator.py:110} INFO -   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/pandas/io/parsers.py", line 710, in read_fwf
[2019-01-27 11:46:46,142] {bash_operator.py:110} INFO -     return _read(filepath_or_buffer, kwds)
[2019-01-27 11:46:46,142] {bash_operator.py:110} INFO -   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/pandas/io/parsers.py", line 440, in _read
[2019-01-27 11:46:46,142] {bash_operator.py:110} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2019-01-27 11:46:46,142] {bash_operator.py:110} INFO -   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/pandas/io/parsers.py", line 787, in __init__
[2019-01-27 11:46:46,142] {bash_operator.py:110} INFO -     self._make_engine(self.engine)
[2019-01-27 11:46:46,142] {bash_operator.py:110} INFO -   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/pandas/io/parsers.py", line 1024, in _make_engine
[2019-01-27 11:46:46,142] {bash_operator.py:110} INFO -     self._engine = klass(self.f, **self.options)
[2019-01-27 11:46:46,142] {bash_operator.py:110} INFO -   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/pandas/io/parsers.py", line 3445, in __init__
[2019-01-27 11:46:46,142] {bash_operator.py:110} INFO -     PythonParser.__init__(self, f, **kwds)
[2019-01-27 11:46:46,142] {bash_operator.py:110} INFO -   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/pandas/io/parsers.py", line 2077, in __init__
[2019-01-27 11:46:46,143] {bash_operator.py:110} INFO -     memory_map=self.memory_map)
[2019-01-27 11:46:46,143] {bash_operator.py:110} INFO -   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/pandas/io/common.py", line 403, in _get_handle
[2019-01-27 11:46:46,143] {bash_operator.py:110} INFO -     f = open(path_or_buf, mode, errors='replace')
[2019-01-27 11:46:46,143] {bash_operator.py:110} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'auto-mpg.data'
[2019-01-27 11:46:46,282] {bash_operator.py:114} INFO - Command exited with return code 1
[2019-01-27 11:46:46,288] {models.py:1760} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/airflow/models.py", line 1659, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/airflow/operators/bash_operator.py", line 118, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2019-01-27 11:46:46,289] {models.py:1789} INFO - All retries failed; marking task as FAILED
[2019-01-27 11:46:46,487] {base_task_runner.py:101} INFO - Job 12: Subtask run_regression Traceback (most recent call last):
[2019-01-27 11:46:46,487] {base_task_runner.py:101} INFO - Job 12: Subtask run_regression   File "/home/brute/apps/anaconda/envs/airflow/bin/airflow", line 32, in <module>
[2019-01-27 11:46:46,487] {base_task_runner.py:101} INFO - Job 12: Subtask run_regression     args.func(args)
[2019-01-27 11:46:46,488] {base_task_runner.py:101} INFO - Job 12: Subtask run_regression   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-01-27 11:46:46,488] {base_task_runner.py:101} INFO - Job 12: Subtask run_regression     return f(*args, **kwargs)
[2019-01-27 11:46:46,488] {base_task_runner.py:101} INFO - Job 12: Subtask run_regression   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/airflow/bin/cli.py", line 490, in run
[2019-01-27 11:46:46,488] {base_task_runner.py:101} INFO - Job 12: Subtask run_regression     _run(args, dag, ti)
[2019-01-27 11:46:46,488] {base_task_runner.py:101} INFO - Job 12: Subtask run_regression   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/airflow/bin/cli.py", line 406, in _run
[2019-01-27 11:46:46,488] {base_task_runner.py:101} INFO - Job 12: Subtask run_regression     pool=args.pool,
[2019-01-27 11:46:46,489] {base_task_runner.py:101} INFO - Job 12: Subtask run_regression   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-01-27 11:46:46,489] {base_task_runner.py:101} INFO - Job 12: Subtask run_regression     return func(*args, **kwargs)
[2019-01-27 11:46:46,489] {base_task_runner.py:101} INFO - Job 12: Subtask run_regression   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/airflow/models.py", line 1659, in _run_raw_task
[2019-01-27 11:46:46,489] {base_task_runner.py:101} INFO - Job 12: Subtask run_regression     result = task_copy.execute(context=context)
[2019-01-27 11:46:46,489] {base_task_runner.py:101} INFO - Job 12: Subtask run_regression   File "/home/brute/apps/anaconda/envs/airflow/lib/python3.6/site-packages/airflow/operators/bash_operator.py", line 118, in execute
[2019-01-27 11:46:46,490] {base_task_runner.py:101} INFO - Job 12: Subtask run_regression     raise AirflowException("Bash command failed")
[2019-01-27 11:46:46,490] {base_task_runner.py:101} INFO - Job 12: Subtask run_regression airflow.exceptions.AirflowException: Bash command failed
[2019-01-27 11:46:48,903] {logging_mixin.py:95} INFO - [2019-01-27 11:46:48,901] {jobs.py:2627} INFO - Task exited with return code 1
